// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.CQRS.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PaymentCommandHandlers_CompleteCoverageFeature : object, Xunit.IClassFixture<PaymentCommandHandlers_CompleteCoverageFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/CQRS/Commands", "Payment Command Handlers - Complete Coverage", ("  As a system\r\n  I want to test all payment command handlers\r\n  So that every cod" +
                "e path, validation, and business rule is covered"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public PaymentCommandHandlers_CompleteCoverageFeature(PaymentCommandHandlers_CompleteCoverageFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("a provider \"Test Provider\" exists with active status", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
            await testRunner.AndAsync("the provider has a service \"Haircut\" priced at 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.AndAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.AndAsync("I have a confirmed booking", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Process payment for booking")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Process payment for booking")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        [Xunit.TraitAttribute("Category", "with-booking")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_ProcessPaymentForBooking()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "happy-path",
                    "with-booking"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Process payment for booking", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table43.AddRow(new string[] {
                            "BookingId",
                            "[Booking:Current:Id]"});
                table43.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table43.AddRow(new string[] {
                            "Currency",
                            "USD"});
                table43.AddRow(new string[] {
                            "Method",
                            "CreditCard"});
                table43.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test"});
                table43.AddRow(new string[] {
                            "CaptureImmediately",
                            "true"});
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with:", ((string)(null)), table43, "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("a Payment aggregate should be created for the booking", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("PaymentCreatedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("PaymentProcessedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment status should be \"Paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Process direct payment (no booking)")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Process direct payment (no booking)")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        [Xunit.TraitAttribute("Category", "direct")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_ProcessDirectPaymentNoBooking()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "happy-path",
                    "direct"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Process direct payment (no booking)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table44.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table44.AddRow(new string[] {
                            "Currency",
                            "USD"});
                table44.AddRow(new string[] {
                            "Method",
                            "CreditCard"});
                table44.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test"});
                await testRunner.WhenAsync("I execute ProcessPaymentCommand without booking ID:", ((string)(null)), table44, "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("a direct Payment aggregate should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should not be linked to a booking", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Payment gateway succeeds")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Payment gateway succeeds")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "gateway-success")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_PaymentGatewaySucceeds()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "gateway-success"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Payment gateway succeeds", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("the payment gateway returns success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("Payment.ProcessCharge should be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("PaymentProcessedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should have a PaymentIntentId", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment status should be \"Paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Payment gateway fails")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Payment gateway fails")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "gateway-failure")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_PaymentGatewayFails()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "gateway-failure"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Payment gateway fails", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("the payment gateway returns failure with error \"Insufficient funds\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("Payment.MarkAsFailed should be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("PaymentFailedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should contain the error message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the command result should indicate failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Invalid amount validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Invalid amount validation")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "amount")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_InvalidAmountValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "validation",
                    "amount"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Invalid amount validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with amount 0.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate amount must be greater than zero", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Negative amount validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Negative amount validation")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "amount-negative")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_NegativeAmountValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "validation",
                    "amount-negative"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Negative amount validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with amount -50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate invalid amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Invalid currency validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Invalid currency validation")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "currency")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_InvalidCurrencyValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "validation",
                    "currency"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Invalid currency validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with currency \"INVALID\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate invalid currency code", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Empty payment method ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Empty payment method ID")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "payment-method-id")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_EmptyPaymentMethodID()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "validation",
                    "payment-method-id"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Empty payment method ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with empty PaymentMethodId", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate PaymentMethodId is required", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Invalid customer ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Invalid customer ID")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "customer-id")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_InvalidCustomerID()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "validation",
                    "customer-id"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Invalid customer ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with invalid customer ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ProcessPaymentCommand - Payment includes metadata")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ProcessPaymentCommand - Payment includes metadata")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "metadata")]
        public async System.Threading.Tasks.Task ProcessPaymentCommand_PaymentIncludesMetadata()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "process",
                    "metadata"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ProcessPaymentCommand - Payment includes metadata", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute ProcessPaymentCommand with custom metadata", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should contain the metadata", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the metadata should be sent to payment gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Capture full authorized amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Capture full authorized amount")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        [Xunit.TraitAttribute("Category", "full")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_CaptureFullAuthorizedAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "happy-path",
                    "full"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Capture full authorized amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have an authorized payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand for full amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("PaymentCapturedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment status should be \"Paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the captured amount should equal authorized amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Capture partial amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Capture partial amount")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        [Xunit.TraitAttribute("Category", "partial")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_CapturePartialAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "happy-path",
                    "partial"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Capture partial amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have an authorized payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand for 50.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("PaymentCapturedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the captured amount should be 50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the remaining authorized amount should be 50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Payment not found")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Payment not found")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "payment-not-found")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_PaymentNotFound()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "validation",
                    "payment-not-found"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Payment not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute CapturePaymentCommand with non-existent payment ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with NotFoundException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate payment not found", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Payment not in authorized state")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Payment not in authorized state")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "not-authorized")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_PaymentNotInAuthorizedState()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "validation",
                    "not-authorized"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Payment not in authorized state", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a completed payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ConflictException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate payment not authorized", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Capture amount exceeds authorized")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Capture amount exceeds authorized")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "amount-exceeds")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_CaptureAmountExceedsAuthorized()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "validation",
                    "amount-exceeds"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Capture amount exceeds authorized", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have an authorized payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand for 150.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate amount exceeds authorized amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Cannot capture zero amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Cannot capture zero amount")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "zero-amount")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_CannotCaptureZeroAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "validation",
                    "zero-amount"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Cannot capture zero amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have an authorized payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand for 0.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Gateway capture fails")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Gateway capture fails")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "gateway-failure")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_GatewayCaptureFails()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "gateway-failure"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Gateway capture fails", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have an authorized payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("the payment gateway capture fails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("the command should fail with PaymentGatewayException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should remain in authorized state", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("CaptureFailedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CapturePaymentCommand - Only provider can capture")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CapturePaymentCommand - Only provider can capture")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "capture")]
        [Xunit.TraitAttribute("Category", "authorization")]
        public async System.Threading.Tasks.Task CapturePaymentCommand_OnlyProviderCanCapture()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "capture",
                    "authorization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CapturePaymentCommand - Only provider can capture", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("there is an authorized payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute CapturePaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ForbiddenException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Full refund")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Full refund")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        [Xunit.TraitAttribute("Category", "full")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_FullRefund()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "happy-path",
                    "full"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Full refund", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table45.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table45.AddRow(new string[] {
                            "Reason",
                            "CustomerRequest"});
                table45.AddRow(new string[] {
                            "Notes",
                            "Customer requested"});
                await testRunner.WhenAsync("I execute RefundPaymentCommand with:", ((string)(null)), table45, "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("PaymentRefundedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment status should be \"Refunded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the refunded amount should be 100.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Partial refund")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Partial refund")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        [Xunit.TraitAttribute("Category", "partial")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_PartialRefund()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "happy-path",
                    "partial"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Partial refund", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand for 50.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("PaymentRefundedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment status should be \"PartiallyRefunded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the refunded amount should be 50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the remaining refundable amount should be 50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Multiple partial refunds")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Multiple partial refunds")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "multiple-partial")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_MultiplePartialRefunds()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "multiple-partial"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Multiple partial refunds", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand for 30.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I execute RefundPaymentCommand for 40.00 USD again", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("both commands should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the total refunded amount should be 70.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment status should be \"PartiallyRefunded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Payment not found")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Payment not found")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "payment-not-found")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_PaymentNotFound()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "validation",
                    "payment-not-found"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Payment not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I execute RefundPaymentCommand with non-existent payment ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with NotFoundException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Cannot refund unpaid payment")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Cannot refund unpaid payment")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "not-paid")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_CannotRefundUnpaidPayment()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "validation",
                    "not-paid"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Cannot refund unpaid payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a pending payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ConflictException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate payment not in refundable state", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Cannot refund already fully refunded payment")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Cannot refund already fully refunded payment")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "already-refunded")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_CannotRefundAlreadyFullyRefundedPayment()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "validation",
                    "already-refunded"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Cannot refund already fully refunded payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a fully refunded payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ConflictException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate payment already refunded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Refund amount exceeds paid amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Refund amount exceeds paid amount")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "amount-exceeds")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_RefundAmountExceedsPaidAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "validation",
                    "amount-exceeds"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Refund amount exceeds paid amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment of 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand for 150.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate refund exceeds paid amount", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Cannot refund zero amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Cannot refund zero amount")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "zero-amount")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_CannotRefundZeroAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "validation",
                    "zero-amount"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Cannot refund zero amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand for 0.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Reason is required")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Reason is required")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "no-reason")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_ReasonIsRequired()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "validation",
                    "no-reason"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Reason is required", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand without a reason", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate reason is required", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Gateway refund fails")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Gateway refund fails")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "gateway-failure")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_GatewayRefundFails()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "gateway-failure"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Gateway refund fails", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("the payment gateway refund fails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("the command should fail with PaymentGatewayException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should remain in paid state", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("RefundFailedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Only provider or admin can refund")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Only provider or admin can refund")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "authorization")]
        [Xunit.TraitAttribute("Category", "provider-only")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_OnlyProviderOrAdminCanRefund()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "authorization",
                    "provider-only"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Only provider or admin can refund", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("there is a paid payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ForbiddenException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Records refund timestamp")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Records refund timestamp")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "timing")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_RecordsRefundTimestamp()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "timing"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Records refund timestamp", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refund should have a timestamp", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the refund metadata should include reason and notes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RefundPaymentCommand - Idempotent for same refund request")]
        [Xunit.TraitAttribute("FeatureTitle", "Payment Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RefundPaymentCommand - Idempotent for same refund request")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "refund")]
        [Xunit.TraitAttribute("Category", "idempotency")]
        public async System.Threading.Tasks.Task RefundPaymentCommand_IdempotentForSameRefundRequest()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "payment",
                    "refund",
                    "idempotency"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RefundPaymentCommand - Idempotent for same refund request", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have a paid payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RefundPaymentCommand with idempotency key \"ref-123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I execute the same RefundPaymentCommand again with same key", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("the second command should return the same result", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("only one refund should be processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PaymentCommandHandlers_CompleteCoverageFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PaymentCommandHandlers_CompleteCoverageFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
