// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.CQRS.Commands
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProviderCommandHandlers_CompleteCoverageFeature : object, Xunit.IClassFixture<ProviderCommandHandlers_CompleteCoverageFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/CQRS/Commands", "Provider Command Handlers - Complete Coverage", "  As a system\r\n  I want to test all critical provider command handlers\r\n  So that" +
                " every code path is validated", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ProviderCommandHandlers_CompleteCoverageFeature(ProviderCommandHandlers_CompleteCoverageFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RegisterProviderCommand - Successful registration")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RegisterProviderCommand - Successful registration")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "register")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task RegisterProviderCommand_SuccessfulRegistration()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "register",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RegisterProviderCommand - Successful registration", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table61.AddRow(new string[] {
                            "BusinessName",
                            "Beautiful Salon"});
                table61.AddRow(new string[] {
                            "Type",
                            "Salon"});
                table61.AddRow(new string[] {
                            "Email",
                            "salon@test.com"});
                table61.AddRow(new string[] {
                            "Phone",
                            "+989121234567"});
                table61.AddRow(new string[] {
                            "City",
                            "Tehran"});
                await testRunner.WhenAsync("I execute RegisterProviderCommand with valid data:", ((string)(null)), table61, "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("a Provider aggregate should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("ProviderRegisteredEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the provider status should be \"PendingVerification\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the provider should be owned by current user", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RegisterProviderCommand - Duplicate business name in same city")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RegisterProviderCommand - Duplicate business name in same city")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "register")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "duplicate-name")]
        public async System.Threading.Tasks.Task RegisterProviderCommand_DuplicateBusinessNameInSameCity()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "register",
                    "validation",
                    "duplicate-name"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RegisterProviderCommand - Duplicate business name in same city", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("a provider \"Existing Salon\" exists in \"Tehran\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute RegisterProviderCommand with business name \"Existing Salon\" in \"Tehran\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ConflictException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate duplicate business name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RegisterProviderCommand - Empty business name")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RegisterProviderCommand - Empty business name")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "register")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "empty-name")]
        public async System.Threading.Tasks.Task RegisterProviderCommand_EmptyBusinessName()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "register",
                    "validation",
                    "empty-name"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RegisterProviderCommand - Empty business name", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RegisterProviderCommand with empty business name", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate business name is required", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RegisterProviderCommand - Business name length validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RegisterProviderCommand - Business name length validation")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "register")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "name-length")]
        public async System.Threading.Tasks.Task RegisterProviderCommand_BusinessNameLengthValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "register",
                    "validation",
                    "name-length"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RegisterProviderCommand - Business name length validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RegisterProviderCommand with business name of 1 character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate business name must be 2-100 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RegisterProviderCommand - Invalid phone format")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RegisterProviderCommand - Invalid phone format")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "register")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "invalid-phone")]
        public async System.Threading.Tasks.Task RegisterProviderCommand_InvalidPhoneFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "register",
                    "validation",
                    "invalid-phone"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RegisterProviderCommand - Invalid phone format", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RegisterProviderCommand with invalid phone \"12345\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate invalid phone format", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="RegisterProviderCommand - Invalid email format")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "RegisterProviderCommand - Invalid email format")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "register")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "invalid-email")]
        public async System.Threading.Tasks.Task RegisterProviderCommand_InvalidEmailFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "register",
                    "validation",
                    "invalid-email"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RegisterProviderCommand - Invalid email format", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute RegisterProviderCommand with invalid email \"notanemail\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ActivateProviderCommand - Admin activates pending provider")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ActivateProviderCommand - Admin activates pending provider")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "activate")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task ActivateProviderCommand_AdminActivatesPendingProvider()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "activate",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ActivateProviderCommand - Admin activates pending provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("a provider exists with status \"PendingVerification\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute ActivateProviderCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("ProviderActivatedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the provider status should be \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the provider should be notified of activation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ActivateProviderCommand - Provider not found")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ActivateProviderCommand - Provider not found")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "activate")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "not-found")]
        public async System.Threading.Tasks.Task ActivateProviderCommand_ProviderNotFound()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "activate",
                    "validation",
                    "not-found"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ActivateProviderCommand - Provider not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute ActivateProviderCommand with non-existent provider ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with NotFoundException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ActivateProviderCommand - Activating already active provider")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ActivateProviderCommand - Activating already active provider")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "activate")]
        [Xunit.TraitAttribute("Category", "idempotency")]
        public async System.Threading.Tasks.Task ActivateProviderCommand_ActivatingAlreadyActiveProvider()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "activate",
                    "idempotency"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ActivateProviderCommand - Activating already active provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("a provider exists with status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute ActivateProviderCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("no ProviderActivatedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the status should remain \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ActivateProviderCommand - Only admin can activate")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "ActivateProviderCommand - Only admin can activate")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "activate")]
        [Xunit.TraitAttribute("Category", "authorization")]
        public async System.Threading.Tasks.Task ActivateProviderCommand_OnlyAdminCanActivate()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "activate",
                    "authorization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ActivateProviderCommand - Only admin can activate", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("a provider exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute ActivateProviderCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ForbiddenException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AddStaffCommand - Add staff member successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "AddStaffCommand - Add staff member successfully")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "staff")]
        [Xunit.TraitAttribute("Category", "add")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task AddStaffCommand_AddStaffMemberSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "staff",
                    "add",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddStaffCommand - Add staff member successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table62.AddRow(new string[] {
                            "FirstName",
                            "John"});
                table62.AddRow(new string[] {
                            "LastName",
                            "Doe"});
                table62.AddRow(new string[] {
                            "Email",
                            "john@test.com"});
                table62.AddRow(new string[] {
                            "Phone",
                            "+1234567890"});
                table62.AddRow(new string[] {
                            "Role",
                            "ServiceProvider"});
                await testRunner.WhenAsync("I execute AddStaffCommand with:", ((string)(null)), table62, "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("StaffAddedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the staff member should be added to provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the staff should have an ID assigned", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AddStaffCommand - Duplicate email validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "AddStaffCommand - Duplicate email validation")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "staff")]
        [Xunit.TraitAttribute("Category", "add")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "duplicate-email")]
        public async System.Threading.Tasks.Task AddStaffCommand_DuplicateEmailValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "staff",
                    "add",
                    "validation",
                    "duplicate-email"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddStaffCommand - Duplicate email validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("the provider has staff with email \"existing@test.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute AddStaffCommand with email \"existing@test.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ConflictException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate duplicate email", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AddStaffCommand - First name required")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "AddStaffCommand - First name required")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "staff")]
        [Xunit.TraitAttribute("Category", "add")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "empty-name")]
        public async System.Threading.Tasks.Task AddStaffCommand_FirstNameRequired()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "staff",
                    "add",
                    "validation",
                    "empty-name"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddStaffCommand - First name required", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute AddStaffCommand with empty first name", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AddStaffCommand - Invalid role validation")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "AddStaffCommand - Invalid role validation")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "staff")]
        [Xunit.TraitAttribute("Category", "add")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "invalid-role")]
        public async System.Threading.Tasks.Task AddStaffCommand_InvalidRoleValidation()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "staff",
                    "add",
                    "validation",
                    "invalid-role"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddStaffCommand - Invalid role validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute AddStaffCommand with invalid role \"InvalidRole\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="AddStaffCommand - Only provider owner can add staff")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "AddStaffCommand - Only provider owner can add staff")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "staff")]
        [Xunit.TraitAttribute("Category", "add")]
        [Xunit.TraitAttribute("Category", "authorization")]
        public async System.Threading.Tasks.Task AddStaffCommand_OnlyProviderOwnerCanAddStaff()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "staff",
                    "add",
                    "authorization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AddStaffCommand - Only provider owner can add staff", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a different provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute AddStaffCommand for another provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ForbiddenException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UpdateBusinessHoursCommand - Update business hours")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UpdateBusinessHoursCommand - Update business hours")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "hours")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task UpdateBusinessHoursCommand_UpdateBusinessHours()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "hours",
                    "update",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UpdateBusinessHoursCommand - Update business hours", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "Day",
                            "IsOpen",
                            "OpenTime",
                            "CloseTime"});
                table63.AddRow(new string[] {
                            "Monday",
                            "true",
                            "09:00",
                            "18:00"});
                table63.AddRow(new string[] {
                            "Sunday",
                            "false",
                            "",
                            ""});
                await testRunner.WhenAsync("I execute UpdateBusinessHoursCommand with:", ((string)(null)), table63, "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("BusinessHoursUpdatedEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the business hours should be updated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UpdateBusinessHoursCommand - Close time before open time")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UpdateBusinessHoursCommand - Close time before open time")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "hours")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "invalid-time-range")]
        public async System.Threading.Tasks.Task UpdateBusinessHoursCommand_CloseTimeBeforeOpenTime()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "hours",
                    "update",
                    "validation",
                    "invalid-time-range"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UpdateBusinessHoursCommand - Close time before open time", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute UpdateBusinessHoursCommand with open 18:00 and close 09:00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate invalid time range", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UpdateBusinessHoursCommand - Overlapping break times")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UpdateBusinessHoursCommand - Overlapping break times")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "hours")]
        [Xunit.TraitAttribute("Category", "update")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "overlapping-breaks")]
        public async System.Threading.Tasks.Task UpdateBusinessHoursCommand_OverlappingBreakTimes()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "hours",
                    "update",
                    "validation",
                    "overlapping-breaks"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UpdateBusinessHoursCommand - Overlapping break times", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "BreakStart",
                            "BreakEnd"});
                table64.AddRow(new string[] {
                            "12:00",
                            "13:00"});
                table64.AddRow(new string[] {
                            "12:30",
                            "13:30"});
                await testRunner.WhenAsync("I execute UpdateBusinessHoursCommand with overlapping breaks:", ((string)(null)), table64, "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UploadGalleryImagesCommand - Upload images successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UploadGalleryImagesCommand - Upload images successfully")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "gallery")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task UploadGalleryImagesCommand_UploadImagesSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "gallery",
                    "upload",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UploadGalleryImagesCommand - Upload images successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute UploadGalleryImagesCommand with 3 valid images", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("3 GalleryImageUploadedEvents should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the images should be stored with thumbnails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("display order should be assigned", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UploadGalleryImagesCommand - Exceeds maximum images")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UploadGalleryImagesCommand - Exceeds maximum images")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "gallery")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "max-count")]
        public async System.Threading.Tasks.Task UploadGalleryImagesCommand_ExceedsMaximumImages()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "gallery",
                    "upload",
                    "validation",
                    "max-count"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UploadGalleryImagesCommand - Exceeds maximum images", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute UploadGalleryImagesCommand with 11 images", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate maximum 10 images allowed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UploadGalleryImagesCommand - File size exceeds limit")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UploadGalleryImagesCommand - File size exceeds limit")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "gallery")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "file-size")]
        public async System.Threading.Tasks.Task UploadGalleryImagesCommand_FileSizeExceedsLimit()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "gallery",
                    "upload",
                    "validation",
                    "file-size"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UploadGalleryImagesCommand - File size exceeds limit", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute UploadGalleryImagesCommand with 12MB image", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate file size exceeded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="UploadGalleryImagesCommand - Invalid file format")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "UploadGalleryImagesCommand - Invalid file format")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "gallery")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "invalid-format")]
        public async System.Threading.Tasks.Task UploadGalleryImagesCommand_InvalidFileFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "gallery",
                    "upload",
                    "validation",
                    "invalid-format"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("UploadGalleryImagesCommand - Invalid file format", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute UploadGalleryImagesCommand with PDF file", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate invalid file type", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CreateProviderDraftCommand - Create draft provider")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CreateProviderDraftCommand - Create draft provider")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "draft")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task CreateProviderDraftCommand_CreateDraftProvider()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "draft",
                    "create",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CreateProviderDraftCommand - Create draft provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I execute CreateProviderDraftCommand with basic info", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("a draft provider should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the status should be \"Drafted\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the registration step should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CreateProviderDraftCommand - Return existing draft")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CreateProviderDraftCommand - Return existing draft")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "draft")]
        [Xunit.TraitAttribute("Category", "create")]
        [Xunit.TraitAttribute("Category", "existing-draft")]
        public async System.Threading.Tasks.Task CreateProviderDraftCommand_ReturnExistingDraft()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "draft",
                    "create",
                    "existing-draft"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CreateProviderDraftCommand - Return existing draft", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I already have a draft provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute CreateProviderDraftCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the existing draft should be returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("no new provider should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CompleteProviderRegistrationCommand - Complete registration")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CompleteProviderRegistrationCommand - Complete registration")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "complete")]
        [Xunit.TraitAttribute("Category", "happy-path")]
        public async System.Threading.Tasks.Task CompleteProviderRegistrationCommand_CompleteRegistration()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "registration",
                    "complete",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CompleteProviderRegistrationCommand - Complete registration", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I have a draft provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the draft has services added", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the draft has staff added", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the draft has working hours configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute CompleteProviderRegistrationCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the provider status should change to \"PendingVerification\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("ProviderRegisteredEvent should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CompleteProviderRegistrationCommand - Missing required data")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CompleteProviderRegistrationCommand - Missing required data")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "complete")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "missing-requirements")]
        public async System.Threading.Tasks.Task CompleteProviderRegistrationCommand_MissingRequiredData()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "registration",
                    "complete",
                    "validation",
                    "missing-requirements"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CompleteProviderRegistrationCommand - Missing required data", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I have a draft provider without services", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute CompleteProviderRegistrationCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ValidationException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate missing required data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="CompleteProviderRegistrationCommand - Provider not in draft status")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Command Handlers - Complete Coverage")]
        [Xunit.TraitAttribute("Description", "CompleteProviderRegistrationCommand - Provider not in draft status")]
        [Xunit.TraitAttribute("Category", "command")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "registration")]
        [Xunit.TraitAttribute("Category", "complete")]
        [Xunit.TraitAttribute("Category", "validation")]
        [Xunit.TraitAttribute("Category", "not-draft")]
        public async System.Threading.Tasks.Task CompleteProviderRegistrationCommand_ProviderNotInDraftStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "command",
                    "provider",
                    "registration",
                    "complete",
                    "validation",
                    "not-draft"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CompleteProviderRegistrationCommand - Provider not in draft status", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I have an active provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I execute CompleteProviderRegistrationCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the command should fail with ConflictException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ProviderCommandHandlers_CompleteCoverageFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ProviderCommandHandlers_CompleteCoverageFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
