// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Payments.Behpardakht
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BehpardakhtPaymentRefundsFeature : object, Xunit.IClassFixture<BehpardakhtPaymentRefundsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Payments/Behpardakht", "Behpardakht Payment Refunds", ("    As a merchant\r\n    I want to refund Behpardakht payments\r\n    So that I can r" +
                "eturn money to customers when needed"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public BehpardakhtPaymentRefundsFeature(BehpardakhtPaymentRefundsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            global::Reqnroll.Table table150 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table150.AddRow(new string[] {
                        "BusinessName",
                        "Test Beauty Salon"});
            table150.AddRow(new string[] {
                        "BusinessType",
                        "BeautySalon"});
            table150.AddRow(new string[] {
                        "Email",
                        "provider@example.com"});
            await testRunner.GivenAsync("a registered provider exists with:", ((string)(null)), table150, "Given ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successfully refund full amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Successfully refund full amount")]
        public async System.Threading.Tasks.Task SuccessfullyRefundFullAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully refund full amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table151 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table151.AddRow(new string[] {
                            "Amount",
                            "500000"});
                table151.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table151.AddRow(new string[] {
                            "RefId",
                            "REF123456"});
                table151.AddRow(new string[] {
                            "SaleOrderId",
                            "100001"});
                table151.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456789"});
                table151.AddRow(new string[] {
                            "CardPan",
                            "6104****1234"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table151, "Given ");
                await testRunner.WhenAsync("I refund 500000 Rials with reason \"Full refund requested\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refunded amount should be 500000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should have status \"Refunded\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successfully refund partial amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Successfully refund partial amount")]
        public async System.Threading.Tasks.Task SuccessfullyRefundPartialAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully refund partial amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table152 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table152.AddRow(new string[] {
                            "Amount",
                            "500000"});
                table152.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table152.AddRow(new string[] {
                            "RefId",
                            "REF123457"});
                table152.AddRow(new string[] {
                            "SaleOrderId",
                            "100002"});
                table152.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456790"});
                table152.AddRow(new string[] {
                            "CardPan",
                            "6104****5678"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table152, "Given ");
                await testRunner.WhenAsync("I refund 200000 Rials with reason \"Partial service cancellation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refunded amount should be 200000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should have status \"PartiallyRefunded\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund multiple partial amounts")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund multiple partial amounts")]
        public async System.Threading.Tasks.Task RefundMultiplePartialAmounts()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund multiple partial amounts", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table153 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table153.AddRow(new string[] {
                            "Amount",
                            "600000"});
                table153.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table153.AddRow(new string[] {
                            "RefId",
                            "REF123458"});
                table153.AddRow(new string[] {
                            "SaleOrderId",
                            "100003"});
                table153.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456791"});
                table153.AddRow(new string[] {
                            "CardPan",
                            "6104****9012"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table153, "Given ");
                await testRunner.AndAsync("the payment has been partially refunded 150000 Rials", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I refund 250000 Rials with reason \"Additional refund\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the total refunded amount should be 400000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fail to refund more than payment amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Fail to refund more than payment amount")]
        public async System.Threading.Tasks.Task FailToRefundMoreThanPaymentAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fail to refund more than payment amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table154 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table154.AddRow(new string[] {
                            "Amount",
                            "300000"});
                table154.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table154.AddRow(new string[] {
                            "RefId",
                            "REF123459"});
                table154.AddRow(new string[] {
                            "SaleOrderId",
                            "100004"});
                table154.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456792"});
                table154.AddRow(new string[] {
                            "CardPan",
                            "6104****3456"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table154, "Given ");
                await testRunner.WhenAsync("I refund 400000 Rials with reason \"Exceeds amount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Refund amount exceeds payment amount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fail to refund more than remaining amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Fail to refund more than remaining amount")]
        public async System.Threading.Tasks.Task FailToRefundMoreThanRemainingAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fail to refund more than remaining amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table155 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table155.AddRow(new string[] {
                            "Amount",
                            "500000"});
                table155.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table155.AddRow(new string[] {
                            "RefId",
                            "REF123460"});
                table155.AddRow(new string[] {
                            "SaleOrderId",
                            "100005"});
                table155.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456793"});
                table155.AddRow(new string[] {
                            "CardPan",
                            "6104****7890"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table155, "Given ");
                await testRunner.AndAsync("the payment has been partially refunded 300000 Rials", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I refund 300000 Rials with reason \"Exceeds remaining\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Refund amount exceeds remaining amount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fail to refund already fully refunded payment")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Fail to refund already fully refunded payment")]
        public async System.Threading.Tasks.Task FailToRefundAlreadyFullyRefundedPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fail to refund already fully refunded payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table156 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table156.AddRow(new string[] {
                            "Amount",
                            "400000"});
                table156.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table156.AddRow(new string[] {
                            "RefId",
                            "REF123461"});
                table156.AddRow(new string[] {
                            "SaleOrderId",
                            "100006"});
                table156.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456794"});
                table156.AddRow(new string[] {
                            "CardPan",
                            "6104****2345"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table156, "Given ");
                await testRunner.AndAsync("the payment has been fully refunded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I refund 100000 Rials with reason \"Already refunded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Payment already fully refunded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund with specific refund reason codes")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund with specific refund reason codes")]
        public async System.Threading.Tasks.Task RefundWithSpecificRefundReasonCodes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund with specific refund reason codes", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table157 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table157.AddRow(new string[] {
                            "Amount",
                            "350000"});
                table157.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table157.AddRow(new string[] {
                            "RefId",
                            "REF123462"});
                table157.AddRow(new string[] {
                            "SaleOrderId",
                            "100007"});
                table157.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456795"});
                table157.AddRow(new string[] {
                            "CardPan",
                            "6104****6789"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table157, "Given ");
                await testRunner.WhenAsync("I refund 350000 Rials with reason \"Customer dissatisfaction\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refund should have reason \"Customer dissatisfaction\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Handle Behpardakht refund gateway error")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Handle Behpardakht refund gateway error")]
        public async System.Threading.Tasks.Task HandleBehpardakhtRefundGatewayError()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle Behpardakht refund gateway error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table158 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table158.AddRow(new string[] {
                            "Amount",
                            "450000"});
                table158.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table158.AddRow(new string[] {
                            "RefId",
                            "REF123463"});
                table158.AddRow(new string[] {
                            "SaleOrderId",
                            "100008"});
                table158.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456796"});
                table158.AddRow(new string[] {
                            "CardPan",
                            "6104****0123"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table158, "Given ");
                await testRunner.AndAsync("Behpardakht gateway returns error for refund", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I refund 450000 Rials with reason \"Gateway error test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain \"Refund failed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund unsettled payment should fail")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund unsettled payment should fail")]
        public async System.Threading.Tasks.Task RefundUnsettledPaymentShouldFail()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund unsettled payment should fail", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table159 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table159.AddRow(new string[] {
                            "Amount",
                            "250000"});
                table159.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table159.AddRow(new string[] {
                            "RefId",
                            "REF123464"});
                table159.AddRow(new string[] {
                            "SaleOrderId",
                            "100009"});
                table159.AddRow(new string[] {
                            "Status",
                            "Verified"});
                await testRunner.GivenAsync("a verified Behpardakht payment exists with:", ((string)(null)), table159, "Given ");
                await testRunner.WhenAsync("I refund 250000 Rials with reason \"Unsettled refund\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Payment must be settled before refund\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Track refund transaction details")]
        [Xunit.TraitAttribute("FeatureTitle", "Behpardakht Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Track refund transaction details")]
        public async System.Threading.Tasks.Task TrackRefundTransactionDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Track refund transaction details", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table160 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table160.AddRow(new string[] {
                            "Amount",
                            "520000"});
                table160.AddRow(new string[] {
                            "Currency",
                            "IRR"});
                table160.AddRow(new string[] {
                            "RefId",
                            "REF123465"});
                table160.AddRow(new string[] {
                            "SaleOrderId",
                            "100010"});
                table160.AddRow(new string[] {
                            "SaleReferenceId",
                            "123456797"});
                table160.AddRow(new string[] {
                            "CardPan",
                            "6104****4567"});
                await testRunner.GivenAsync("a completed Behpardakht payment exists with:", ((string)(null)), table160, "Given ");
                await testRunner.WhenAsync("I refund 520000 Rials with reason \"Full service cancellation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table161 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table161.AddRow(new string[] {
                            "Amount",
                            "520000"});
                table161.AddRow(new string[] {
                            "Reason",
                            "Full service cancellation"});
                table161.AddRow(new string[] {
                            "Status",
                            "Completed"});
                table161.AddRow(new string[] {
                            "RefundMethod",
                            "Behpardakht"});
                await testRunner.AndAsync("a refund transaction should be recorded with:", ((string)(null)), table161, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BehpardakhtPaymentRefundsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BehpardakhtPaymentRefundsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
