// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Providers
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProviderManagementFeature : object, Xunit.IClassFixture<ProviderManagementFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Providers", "Provider Management", ("  As a provider and admin\r\n  I want to manage provider profiles and settings\r\n  S" +
                "o that provider information is accurate and up-to-date"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ProviderManagementFeature(ProviderManagementFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("a provider \"Test Salon\" exists with active status", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="View provider profile")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "View provider profile")]
        [Xunit.TraitAttribute("Category", "smoke")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "view")]
        public async System.Threading.Tasks.Task ViewProviderProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "provider",
                    "profile",
                    "view"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View provider profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/providers/{providerId}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain complete provider information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider updates their own profile")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider updates their own profile")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "profile")]
        [Xunit.TraitAttribute("Category", "update")]
        public async System.Threading.Tasks.Task ProviderUpdatesTheirOwnProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "profile",
                    "update"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider updates their own profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table313 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table313.AddRow(new string[] {
                            "FullName",
                            "John Doe"});
                table313.AddRow(new string[] {
                            "Email",
                            "newemail@test.com"});
                table313.AddRow(new string[] {
                            "ProfileImageUrl",
                            "/uploads/profile.png"});
                await testRunner.WhenAsync("I send a PUT request to update provider profile with:", ((string)(null)), table313, "When ");
                await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the provider profile should be updated in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider updates business information")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider updates business information")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "business")]
        [Xunit.TraitAttribute("Category", "update")]
        public async System.Threading.Tasks.Task ProviderUpdatesBusinessInformation()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "business",
                    "update"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider updates business information", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table314 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table314.AddRow(new string[] {
                            "BusinessName",
                            "Updated Salon Name"});
                table314.AddRow(new string[] {
                            "Description",
                            "New description"});
                table314.AddRow(new string[] {
                            "PhoneNumber",
                            "+989123456789"});
                table314.AddRow(new string[] {
                            "Website",
                            "https://newsalon.com"});
                await testRunner.WhenAsync("I send a PUT request to update business info with:", ((string)(null)), table314, "When ");
                await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the business information should be updated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider uploads profile image")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider uploads profile image")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "image")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "profile")]
        public async System.Threading.Tasks.Task ProviderUploadsProfileImage()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "image",
                    "upload",
                    "profile"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider uploads profile image", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I upload a valid profile image", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain the image URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the image should be accessible at the URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider uploads business logo")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider uploads business logo")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "image")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "logo")]
        public async System.Threading.Tasks.Task ProviderUploadsBusinessLogo()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "image",
                    "upload",
                    "logo"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider uploads business logo", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I upload a valid business logo", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the logo should be stored correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot upload image exceeding size limit")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Cannot upload image exceeding size limit")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "image")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "size")]
        public async System.Threading.Tasks.Task CannotUploadImageExceedingSizeLimit()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "image",
                    "upload",
                    "negative",
                    "size"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cannot upload image exceeding size limit", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I upload an image larger than 10MB", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate file size exceeded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot upload invalid image format")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Cannot upload invalid image format")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "image")]
        [Xunit.TraitAttribute("Category", "upload")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "format")]
        public async System.Threading.Tasks.Task CannotUploadInvalidImageFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "image",
                    "upload",
                    "negative",
                    "format"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cannot upload invalid image format", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I upload a file with unsupported format", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate invalid file type", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search providers by business name")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Search providers by business name")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "search")]
        public async System.Threading.Tasks.Task SearchProvidersByBusinessName()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "search"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search providers by business name", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are 10 providers in the system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/providers/search?searchTerm=Beauty\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the results should contain only providers matching \"Beauty\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search with pagination")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Search with pagination")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "search")]
        [Xunit.TraitAttribute("Category", "pagination")]
        public async System.Threading.Tasks.Task SearchWithPagination()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "search",
                    "pagination"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search with pagination", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are 15 providers in the system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/providers/search?pageNumber=1&pageSize=5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain exactly 5 providers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("pagination metadata should show correct total count", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Find providers by location")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Find providers by location")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "location")]
        public async System.Threading.Tasks.Task FindProvidersByLocation()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "location"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find providers by location", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("providers exist in various locations", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync(("I send a GET request to find providers near latitude 35.6892, longitude 51.3890 w" +
                        "ithin 10km"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("all returned providers should be within the specified radius", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin activates a provider")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Admin activates a provider")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "status")]
        [Xunit.TraitAttribute("Category", "activate")]
        [Xunit.TraitAttribute("Category", "admin")]
        public async System.Threading.Tasks.Task AdminActivatesAProvider()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "status",
                    "activate",
                    "admin"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin activates a provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("the provider status is \"PendingVerification\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I send a POST request to activate the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the provider status should be \"Active\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin deactivates a provider")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Admin deactivates a provider")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "status")]
        [Xunit.TraitAttribute("Category", "deactivate")]
        public async System.Threading.Tasks.Task AdminDeactivatesAProvider()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "status",
                    "deactivate"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin deactivates a provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a POST request to deactivate the provider with reason \"Policy violation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the provider status should be \"Inactive\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider views their own status")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider views their own status")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "status")]
        [Xunit.TraitAttribute("Category", "view")]
        public async System.Threading.Tasks.Task ProviderViewsTheirOwnStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "status",
                    "view"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider views their own status", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/providers/current/status\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain current status and details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin views providers by status")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Admin views providers by status")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "status")]
        [Xunit.TraitAttribute("Category", "bystatus")]
        [Xunit.TraitAttribute("Category", "admin")]
        public async System.Threading.Tasks.Task AdminViewsProvidersByStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "status",
                    "bystatus",
                    "admin"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin views providers by status", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("there are providers with various statuses", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/providers/by-status/Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("all returned providers should have status \"Active\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider cannot update another provider\'s profile")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider cannot update another provider\'s profile")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "unauthorized")]
        [Xunit.TraitAttribute("Category", "update")]
        public async System.Threading.Tasks.Task ProviderCannotUpdateAnotherProvidersProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "negative",
                    "unauthorized",
                    "update"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider cannot update another provider\'s profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("another provider \"Competitor\" exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I am authenticated as the first provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I send a PUT request to update the competitor\'s profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot update with invalid phone number")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Cannot update with invalid phone number")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "invalid-phone")]
        public async System.Threading.Tasks.Task CannotUpdateWithInvalidPhoneNumber()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "negative",
                    "invalid-phone"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cannot update with invalid phone number", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a PUT request to update business info with invalid phone \"invalid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider updates their settings")]
        [Xunit.TraitAttribute("FeatureTitle", "Provider Management")]
        [Xunit.TraitAttribute("Description", "Provider updates their settings")]
        [Xunit.TraitAttribute("Category", "provider")]
        [Xunit.TraitAttribute("Category", "settings")]
        public async System.Threading.Tasks.Task ProviderUpdatesTheirSettings()
        {
            string[] tagsOfScenario = new string[] {
                    "provider",
                    "settings"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider updates their settings", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table315 = new global::Reqnroll.Table(new string[] {
                            "Setting",
                            "Value"});
                table315.AddRow(new string[] {
                            "AllowOnlineBooking",
                            "true"});
                table315.AddRow(new string[] {
                            "RequireBookingApproval",
                            "false"});
                table315.AddRow(new string[] {
                            "BookingLeadTime",
                            "24"});
                await testRunner.WhenAsync("I update provider settings:", ((string)(null)), table315, "When ");
                await testRunner.ThenAsync("the response status code should be 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the settings should be persisted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ProviderManagementFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ProviderManagementFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
