using Booksy.ServiceCatalog.Domain.Aggregates.BookingAggregate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Booksy.ServiceCatalog.Infrastructure.Persistence.Configurations
{
    /// <summary>
    /// <see cref="BookingHistoryEntry"/> is a child of the Booking aggregate (Booking.History) mapped by convention.
    /// Its Id is generated by the domain (<c>Guid.NewGuid()</c>), so it must be <c>ValueGeneratedNever</c> — otherwise
    /// EF's graph-attach heuristic tracks a history entry appended to an already-loaded booking as Modified, producing
    /// a phantom UPDATE (0 rows → DbUpdateConcurrencyException) that broke every booking state transition
    /// (confirm / cancel / reschedule / complete). Same class of defect as Payment.Transactions
    /// (see fix-aggregate-persistence-concurrency). Model-only change; the existing table/columns are unchanged.
    /// </summary>
    public sealed class BookingHistoryEntryConfiguration : IEntityTypeConfiguration<BookingHistoryEntry>
    {
        public void Configure(EntityTypeBuilder<BookingHistoryEntry> builder)
        {
            builder.ToTable("BookingHistoryEntry", "ServiceCatalog");
            builder.HasKey(h => h.Id);
            builder.Property(h => h.Id).ValueGeneratedNever();
        }
    }
}
