using Booksy.Core.Application.Abstractions.Services;
using Booksy.ServiceCatalog.Infrastructure.Persistence.Context;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using NSubstitute;

namespace Booksy.ArchitectureTests;

/// <summary>
/// Enforces ADR-005 as a test rather than a paragraph.
///
/// <para><b>The rule.</b> A child entity whose key is generated by the domain (a client-side
/// <see cref="Guid"/>) must be mapped <c>ValueGeneratedNever()</c>. Left as <c>ValueGeneratedOnAdd</c>,
/// EF's graph-attach heuristic classifies a newly-appended child as <c>Modified</c> rather than
/// <c>Added</c>, emits a phantom <c>UPDATE … WHERE Id = &lt;new-guid&gt;</c>, matches zero rows, and
/// throws <c>DbUpdateConcurrencyException</c> on save.</para>
///
/// <para><b>Why this is a test and not a comment.</b> ADR-005 documented the rule after it cost 41 red
/// integration tests. It has since been violated <b>four more times</b>: <c>Booking.TotalPrice</c> and
/// <c>Booking.Id</c>, <c>BookingHistoryEntry.Id</c>, and — found during the reschedule fix — the owned
/// value objects handed to a successor booking by <c>Booking.Reschedule</c> plus the shared
/// <c>Price</c>/<c>BookingPolicy</c> instances in <c>CreateBookingRequest</c>. A rule that keeps being
/// broken wants an assertion.</para>
///
/// <para><b>Scope, and why it is what it is.</b> The hazard is graph-attach of a <i>child</i>, so the
/// rule covers owned types and non-owned entities reached through a collection navigation.
/// <c>BookingHistoryEntry</c> — the instance ADR-005 names — is precisely the second kind: a plain
/// entity, not an owned one, so an owned-only rule would have missed it. Aggregate roots that are
/// <c>Add</c>ed explicitly are deliberately out of scope: EF marks them <c>Added</c> regardless of
/// <c>ValueGenerated</c>, so <c>OnAdd</c> on a root is untidy but not a defect. Six such roots exist
/// today (see <c>Roots_With_OnAdd_Guid_Keys_Are_Recorded_Not_Enforced</c>).</para>
///
/// <para><b>Why it inspects the model, not the source.</b> This is an EF mapping property, so
/// NetArchTest (which analyses type dependencies) cannot see it. The model is built with a real Npgsql
/// provider but never connected — <c>DbContext.Model</c> comes from the configuration alone — so this
/// needs no database and runs in the unit tier.</para>
/// </summary>
public class EfOwnedEntityKeyConventionTests
{
    private static IModel BuildServiceCatalogModel()
    {
        var options = new DbContextOptionsBuilder<ServiceCatalogDbContext>()
            // A syntactically valid connection string is enough: the model is derived from
            // OnModelCreating, and nothing here ever opens a connection.
            .UseNpgsql("Host=localhost;Database=model-only;Username=none;Password=none")
            .Options;

        using var context = new ServiceCatalogDbContext(
            options,
            Substitute.For<ICurrentUserService>(),
            Substitute.For<IDateTimeProvider>());

        return context.Model;
    }

    private static IEnumerable<(IEntityType Entity, IProperty Key)> DomainGeneratedGuidKeys(IModel model)
    {
        foreach (var entityType in model.GetEntityTypes())
        {
            var primaryKey = entityType.FindPrimaryKey();
            if (primaryKey is null)
            {
                continue;
            }

            foreach (var property in primaryKey.Properties)
            {
                // Shadow properties are EF's own synthesised FKs, and non-GUID keys are generated by
                // the store (int identity) or by EF (owned-collection ordinals) by design.
                if (property.ClrType != typeof(Guid) && property.ClrType != typeof(Guid?))
                {
                    continue;
                }

                if (property.IsShadowProperty())
                {
                    continue;
                }

                yield return (entityType, property);
            }
        }
    }

    /// <summary>
    /// Every child entity reachable by graph-attach — owned types, plus plain entities on a collection
    /// navigation — must declare its domain-generated GUID key never-generated.
    /// </summary>
    [Fact]
    public void Graph_Attached_Children_With_Guid_Keys_Must_Be_ValueGeneratedNever()
    {
        var model = BuildServiceCatalogModel();

        var collectionChildren = model.GetEntityTypes()
            .SelectMany(t => t.GetNavigations())
            .Where(n => n.IsCollection)
            .Select(n => n.TargetEntityType)
            .ToHashSet();

        var offenders = DomainGeneratedGuidKeys(model)
            .Where(x => x.Entity.IsOwned() || collectionChildren.Contains(x.Entity))
            .Where(x => x.Key.ValueGenerated != ValueGenerated.Never)
            .Select(x => $"{x.Entity.DisplayName()}.{x.Key.Name} " +
                         $"is {x.Key.ValueGenerated}, expected {ValueGenerated.Never}")
            .ToList();

        offenders.Should().BeEmpty(
            "ADR-005: a graph-attached child whose GUID key is not ValueGeneratedNever() makes EF " +
            "classify a newly-appended child as Modified, emitting a phantom UPDATE that matches no row " +
            "and throws DbUpdateConcurrencyException on save. Add .ValueGeneratedNever() to the key in " +
            "this type's EF configuration. Offenders:" + Environment.NewLine + "  " +
            string.Join(Environment.NewLine + "  ", offenders));
    }

    /// <summary>
    /// The child collections ADR-005 names explicitly, pinned by name so the specific regressions stay
    /// legible even if the general sweep's filters ever drift.
    /// </summary>
    [Theory]
    [InlineData("Payment", "Transactions")]
    [InlineData("Notification", "DeliveryAttempts")]
    [InlineData("Service", "PriceTiers")]
    [InlineData("Booking", "History")]
    public void Named_Child_Collections_From_ADR005_Keep_Their_Never_Generated_Keys(
        string aggregateName, string navigationName)
    {
        var model = BuildServiceCatalogModel();

        var aggregate = model.GetEntityTypes()
            .FirstOrDefault(t => !t.IsOwned() && t.ClrType.Name == aggregateName);

        Assert.True(
            aggregate is not null,
            $"Aggregate '{aggregateName}' is not in the ServiceCatalog model. If it was renamed, " +
            "update this Theory's data so ADR-005's named regressions stay pinned.");

        var navigation = aggregate!.GetNavigations().FirstOrDefault(n => n.Name == navigationName);

        Assert.True(
            navigation is not null,
            $"'{aggregateName}.{navigationName}' is not a navigation on the model. If it was renamed, " +
            "update this Theory's data.");

        // Deliberately not asserting IsOwned: BookingHistoryEntry is a plain entity on a collection
        // navigation, not an owned type, and it is subject to exactly the same phantom-UPDATE bug.
        var childType = navigation!.TargetEntityType;

        var guidKeys = childType.FindPrimaryKey()!.Properties
            .Where(p => p.ClrType == typeof(Guid) && !p.IsShadowProperty())
            .ToList();

        guidKeys.Should().NotBeEmpty(
            $"{childType.DisplayName()} is expected to have a domain-generated GUID key");

        guidKeys.Should().OnlyContain(
            p => p.ValueGenerated == ValueGenerated.Never,
            $"ADR-005 names {aggregateName}.{navigationName} as a fixed instance of the phantom-UPDATE bug");
    }

    /// <summary>
    /// Aggregate roots with <c>OnAdd</c> GUID keys are recorded here rather than enforced.
    ///
    /// <para>They are not defects: a root is <c>Add</c>ed explicitly, and EF marks it <c>Added</c>
    /// regardless of <c>ValueGenerated</c>, so the phantom-UPDATE path never applies. They are however
    /// inconsistent — their ids are domain-generated, so <c>Never</c> would state the truth — and any
    /// one of them <b>would</b> become a live ADR-005 defect the moment it gained a collection-navigation
    /// parent. This test fails if that set changes, so a new root either gets <c>Never</c> or gets
    /// consciously added to the list.</para>
    /// </summary>
    [Fact]
    public void Roots_With_OnAdd_Guid_Keys_Are_Recorded_Not_Enforced()
    {
        var model = BuildServiceCatalogModel();

        var collectionChildren = model.GetEntityTypes()
            .SelectMany(t => t.GetNavigations())
            .Where(n => n.IsCollection)
            .Select(n => n.TargetEntityType)
            .ToHashSet();

        var roots = DomainGeneratedGuidKeys(model)
            .Where(x => !x.Entity.IsOwned() && !collectionChildren.Contains(x.Entity))
            .Where(x => x.Key.ValueGenerated != ValueGenerated.Never)
            .Select(x => x.Entity.ClrType.Name)
            .Distinct()
            .OrderBy(x => x)
            .ToList();

        roots.Should().BeEquivalentTo(
            new[]
            {
                "MembershipAuditEntry",
                "OrganizationMembership",
                "ProviderAvailability",
                "ProviderInvitation",
                "Review",
            },
            "this list is a snapshot, not an approval. If it grew, prefer .ValueGeneratedNever() on the " +
            "new root's key — its id is domain-generated — and if the root is now reachable through a " +
            "collection navigation, Never is mandatory, not stylistic");
    }
}
