// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.EdgeCases
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AuthorizationAndSecurityFeature : object, Xunit.IClassFixture<AuthorizationAndSecurityFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/EdgeCases", "Authorization and Security", ("  As a system\r\n  I want to enforce proper authorization\r\n  So that users can only" +
                " access their own data and perform allowed operations"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public AuthorizationAndSecurityFeature(AuthorizationAndSecurityFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Customer can only view their own bookings")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Customer can only view their own bookings")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "authorization")]
        [Xunit.TraitAttribute("Category", "customer")]
        public async System.Threading.Tasks.Task CustomerCanOnlyViewTheirOwnBookings()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "authorization",
                    "customer"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Customer can only view their own bookings", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as customer \"alice@test.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("another customer \"bob@test.com\" has bookings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I try to view Bob\'s bookings", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider can only manage their own services")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Provider can only manage their own services")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "authorization")]
        [Xunit.TraitAttribute("Category", "provider")]
        public async System.Threading.Tasks.Task ProviderCanOnlyManageTheirOwnServices()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "authorization",
                    "provider"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider can only manage their own services", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as provider \"Salon A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("another provider \"Salon B\" exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I try to add a service to Salon B", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Only admins can access admin endpoints")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Only admins can access admin endpoints")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "authorization")]
        [Xunit.TraitAttribute("Category", "admin-only")]
        [Xunit.InlineDataAttribute("customer", "403", new string[0])]
        [Xunit.InlineDataAttribute("provider", "403", new string[0])]
        [Xunit.InlineDataAttribute("admin", "200", new string[0])]
        public async System.Threading.Tasks.Task OnlyAdminsCanAccessAdminEndpoints(string role, string statusCode, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "security",
                    "authorization",
                    "admin-only"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Role", role);
            argumentsOfScenario.Add("StatusCode", statusCode);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only admins can access admin endpoints", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync(string.Format("I am authenticated as a {0}", role), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a request to an admin-only endpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync(string.Format("the response status code should be {0}", statusCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Providers cannot see each other\'s financial data")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Providers cannot see each other\'s financial data")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "data-isolation")]
        public async System.Threading.Tasks.Task ProvidersCannotSeeEachOthersFinancialData()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "data-isolation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Providers cannot see each other\'s financial data", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I am authenticated as provider \"Salon A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("provider \"Salon B\" has financial data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I try to view Salon B\'s earnings", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="System is protected against SQL injection")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "System is protected against SQL injection")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "sql-injection")]
        public async System.Threading.Tasks.Task SystemIsProtectedAgainstSQLInjection()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "sql-injection"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System is protected against SQL injection", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.WhenAsync("I send a request with SQL injection in the search term", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the request should be safely handled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("no database error should occur", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="System sanitizes user input to prevent XSS")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "System sanitizes user input to prevent XSS")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "xss")]
        public async System.Threading.Tasks.Task SystemSanitizesUserInputToPreventXSS()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "xss"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System sanitizes user input to prevent XSS", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.WhenAsync("I create a service with malicious script in the description", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the script should be sanitized", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the stored data should be safe", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Rate limiting prevents abuse")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Rate limiting prevents abuse")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "rate-limiting")]
        public async System.Threading.Tasks.Task RateLimitingPreventsAbuse()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "rate-limiting"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rate limiting prevents abuse", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.WhenAsync("I send 100 requests in 1 minute", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("after the limit, requests should be throttled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should receive 429 status code", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Expired authentication tokens are rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Expired authentication tokens are rejected")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "token-expiry")]
        public async System.Threading.Tasks.Task ExpiredAuthenticationTokensAreRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "token-expiry"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Expired authentication tokens are rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I have an expired authentication token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a request with the expired token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the error should indicate token expired", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Password reset requires verification")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Password reset requires verification")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "password-reset")]
        public async System.Threading.Tasks.Task PasswordResetRequiresVerification()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "password-reset"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Password reset requires verification", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.WhenAsync("I request a password reset for \"user@test.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("a verification code should be sent", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the password cannot be changed without the code", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sensitive data is not exposed in responses")]
        [Xunit.TraitAttribute("FeatureTitle", "Authorization and Security")]
        [Xunit.TraitAttribute("Description", "Sensitive data is not exposed in responses")]
        [Xunit.TraitAttribute("Category", "security")]
        [Xunit.TraitAttribute("Category", "sensitive-data")]
        public async System.Threading.Tasks.Task SensitiveDataIsNotExposedInResponses()
        {
            string[] tagsOfScenario = new string[] {
                    "security",
                    "sensitive-data"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Sensitive data is not exposed in responses", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.WhenAsync("I view my user profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response should not contain password hash", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("payment method details should be masked", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AuthorizationAndSecurityFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AuthorizationAndSecurityFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
