// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Payments
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FinancialReportingAndEarningsFeature : object, Xunit.IClassFixture<FinancialReportingAndEarningsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Payments", "Financial Reporting and Earnings", ("  As a provider and admin\r\n  I want to view financial reports and earnings\r\n  So " +
                "that I can track business performance"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public FinancialReportingAndEarningsFeature(FinancialReportingAndEarningsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("a provider \"Successful Salon\" exists with active status", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
            await testRunner.AndAsync("the provider has business hours configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.AndAsync("the provider has multiple services", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.AndAsync("the provider has completed bookings with payments over the last 30 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider views earnings for a date range")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Provider views earnings for a date range")]
        [Xunit.TraitAttribute("Category", "smoke")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "earnings")]
        public async System.Threading.Tasks.Task ProviderViewsEarningsForADateRange()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "financial",
                    "earnings"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider views earnings for a date range", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table176 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table176.AddRow(new string[] {
                            "StartDate",
                            "30 days ago"});
                table176.AddRow(new string[] {
                            "EndDate",
                            "today"});
                await testRunner.WhenAsync("I send a GET request to provider earnings with:", ((string)(null)), table176, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table177 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table177.AddRow(new string[] {
                            "GrossEarnings",
                            "500.00"});
                table177.AddRow(new string[] {
                            "CommissionAmount",
                            "75.00"});
                table177.AddRow(new string[] {
                            "NetEarnings",
                            "425.00"});
                table177.AddRow(new string[] {
                            "TotalPayments",
                            "5"});
                await testRunner.AndAsync("the response should contain earnings summary:", ((string)(null)), table177, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Earnings report shows daily breakdown")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Earnings report shows daily breakdown")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "earnings")]
        [Xunit.TraitAttribute("Category", "breakdown")]
        public async System.Threading.Tasks.Task EarningsReportShowsDailyBreakdown()
        {
            string[] tagsOfScenario = new string[] {
                    "financial",
                    "earnings",
                    "breakdown"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Earnings report shows daily breakdown", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send a GET request to provider earnings for last 7 days", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should include earnings by date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("each date should show number of payments and amounts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Filter earnings by date range")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Filter earnings by date range")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "earnings")]
        [Xunit.TraitAttribute("Category", "filter")]
        [Xunit.InlineDataAttribute("last 7 days", new string[0])]
        [Xunit.InlineDataAttribute("last 30 days", new string[0])]
        [Xunit.InlineDataAttribute("last 90 days", new string[0])]
        public async System.Threading.Tasks.Task FilterEarningsByDateRange(string period, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "financial",
                    "earnings",
                    "filter"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Period", period);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter earnings by date range", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync(string.Format("I send a GET request to earnings for \"{0}\"", period), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync(string.Format("the response should only include payments from \"{0}\"", period), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider cannot view other provider\'s earnings")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Provider cannot view other provider\'s earnings")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "unauthorized")]
        public async System.Threading.Tasks.Task ProviderCannotViewOtherProvidersEarnings()
        {
            string[] tagsOfScenario = new string[] {
                    "financial",
                    "negative",
                    "unauthorized"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider cannot view other provider\'s earnings", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("another provider \"Competitor Salon\" exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I am authenticated as the first provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I send a GET request to view the competitor\'s earnings", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin views earnings across all providers")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Admin views earnings across all providers")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "admin")]
        [Xunit.TraitAttribute("Category", "allproviders")]
        public async System.Threading.Tasks.Task AdminViewsEarningsAcrossAllProviders()
        {
            string[] tagsOfScenario = new string[] {
                    "financial",
                    "admin",
                    "allproviders"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin views earnings across all providers", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("there are 5 providers with earnings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/financial/summary\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should show platform-wide financial summary", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Earnings calculated in correct currency")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Earnings calculated in correct currency")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "currency")]
        public async System.Threading.Tasks.Task EarningsCalculatedInCorrectCurrency()
        {
            string[] tagsOfScenario = new string[] {
                    "financial",
                    "currency"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Earnings calculated in correct currency", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the provider operates in USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("all payments are in USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I view provider earnings", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("all amounts should be in USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("currency conversions should not be applied", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refunds correctly reduce earnings")]
        [Xunit.TraitAttribute("FeatureTitle", "Financial Reporting and Earnings")]
        [Xunit.TraitAttribute("Description", "Refunds correctly reduce earnings")]
        [Xunit.TraitAttribute("Category", "financial")]
        [Xunit.TraitAttribute("Category", "refunds-impact")]
        public async System.Threading.Tasks.Task RefundsCorrectlyReduceEarnings()
        {
            string[] tagsOfScenario = new string[] {
                    "financial",
                    "refunds-impact"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refunds correctly reduce earnings", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am authenticated as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("the provider has 5 payments totaling 500.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("1 payment of 100.00 USD was refunded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I view provider earnings", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the gross earnings should reflect the refund", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("net earnings should be calculated after refunds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FinancialReportingAndEarningsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FinancialReportingAndEarningsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
