// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Payments
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProcessPaymentFeature : object, Xunit.IClassFixture<ProcessPaymentFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Payments", "Process Payment", "  As a customer\r\n  I want to process payments for my bookings\r\n  So that I can se" +
                "cure my appointments", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ProcessPaymentFeature(ProcessPaymentFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("a provider \"Test Provider\" exists with active status", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
            await testRunner.AndAsync("the provider has a service \"Haircut\" priced at 100.00 USD", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.AndAsync("I am authenticated as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            await testRunner.AndAsync("I have a confirmed booking for \"Haircut\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Process payment with immediate capture")]
        [Xunit.TraitAttribute("FeatureTitle", "Process Payment")]
        [Xunit.TraitAttribute("Description", "Process payment with immediate capture")]
        [Xunit.TraitAttribute("Category", "smoke")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        public async System.Threading.Tasks.Task ProcessPaymentWithImmediateCapture()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "payment",
                    "process"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process payment with immediate capture", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table185 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table185.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table185.AddRow(new string[] {
                            "Currency",
                            "USD"});
                table185.AddRow(new string[] {
                            "PaymentMethod",
                            "CreditCard"});
                table185.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test_card"});
                table185.AddRow(new string[] {
                            "CaptureImmediately",
                            "true"});
                await testRunner.WhenAsync("I send a POST request to process a payment with:", ((string)(null)), table185, "When ");
                await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table186 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table186.AddRow(new string[] {
                            "Status",
                            "Paid"});
                table186.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table186.AddRow(new string[] {
                            "Currency",
                            "USD"});
                await testRunner.AndAsync("the response should contain a payment with:", ((string)(null)), table186, "And ");
                await testRunner.AndAsync("a payment should exist in the database with status \"Paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Authorize payment without immediate capture")]
        [Xunit.TraitAttribute("FeatureTitle", "Process Payment")]
        [Xunit.TraitAttribute("Description", "Authorize payment without immediate capture")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        public async System.Threading.Tasks.Task AuthorizePaymentWithoutImmediateCapture()
        {
            string[] tagsOfScenario = new string[] {
                    "payment",
                    "process"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Authorize payment without immediate capture", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table187 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table187.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table187.AddRow(new string[] {
                            "Currency",
                            "USD"});
                table187.AddRow(new string[] {
                            "PaymentMethod",
                            "CreditCard"});
                table187.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test_card"});
                table187.AddRow(new string[] {
                            "CaptureImmediately",
                            "false"});
                await testRunner.WhenAsync("I send a POST request to process a payment with:", ((string)(null)), table187, "When ");
                await testRunner.ThenAsync("the response status code should be 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table188 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table188.AddRow(new string[] {
                            "Status",
                            "Paid"});
                await testRunner.AndAsync("the response should contain a payment with:", ((string)(null)), table188, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot process payment with invalid amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Process Payment")]
        [Xunit.TraitAttribute("Description", "Cannot process payment with invalid amount")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "validation")]
        public async System.Threading.Tasks.Task CannotProcessPaymentWithInvalidAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "payment",
                    "process",
                    "negative",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cannot process payment with invalid amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table189 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table189.AddRow(new string[] {
                            "Amount",
                            "-50.00"});
                table189.AddRow(new string[] {
                            "Currency",
                            "USD"});
                table189.AddRow(new string[] {
                            "PaymentMethod",
                            "CreditCard"});
                table189.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test_card"});
                table189.AddRow(new string[] {
                            "CaptureImmediately",
                            "true"});
                await testRunner.WhenAsync("I send a POST request to process a payment with:", ((string)(null)), table189, "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot process payment with invalid currency")]
        [Xunit.TraitAttribute("FeatureTitle", "Process Payment")]
        [Xunit.TraitAttribute("Description", "Cannot process payment with invalid currency")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "negative")]
        [Xunit.TraitAttribute("Category", "validation")]
        public async System.Threading.Tasks.Task CannotProcessPaymentWithInvalidCurrency()
        {
            string[] tagsOfScenario = new string[] {
                    "payment",
                    "process",
                    "negative",
                    "validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cannot process payment with invalid currency", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table190 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table190.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table190.AddRow(new string[] {
                            "Currency",
                            "INVALID"});
                table190.AddRow(new string[] {
                            "PaymentMethod",
                            "CreditCard"});
                table190.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test_card"});
                table190.AddRow(new string[] {
                            "CaptureImmediately",
                            "true"});
                await testRunner.WhenAsync("I send a POST request to process a payment with:", ((string)(null)), table190, "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot process payment without authentication")]
        [Xunit.TraitAttribute("FeatureTitle", "Process Payment")]
        [Xunit.TraitAttribute("Description", "Cannot process payment without authentication")]
        [Xunit.TraitAttribute("Category", "payment")]
        [Xunit.TraitAttribute("Category", "process")]
        [Xunit.TraitAttribute("Category", "negative")]
        public async System.Threading.Tasks.Task CannotProcessPaymentWithoutAuthentication()
        {
            string[] tagsOfScenario = new string[] {
                    "payment",
                    "process",
                    "negative"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cannot process payment without authentication", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am not authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table191 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table191.AddRow(new string[] {
                            "Amount",
                            "100.00"});
                table191.AddRow(new string[] {
                            "Currency",
                            "USD"});
                table191.AddRow(new string[] {
                            "PaymentMethod",
                            "CreditCard"});
                table191.AddRow(new string[] {
                            "PaymentMethodId",
                            "pm_test_card"});
                table191.AddRow(new string[] {
                            "CaptureImmediately",
                            "true"});
                await testRunner.WhenAsync("I send a POST request to process a payment with:", ((string)(null)), table191, "When ");
                await testRunner.ThenAsync("the response status code should be 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ProcessPaymentFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ProcessPaymentFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
