// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Payments.ZarinPal
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ZarinPalPaymentVerificationFeature : object, Xunit.IClassFixture<ZarinPalPaymentVerificationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Payments/ZarinPal", "ZarinPal Payment Verification", ("    As a customer\r\n    I want to verify my payment after completing it on ZarinPa" +
                "l\r\n    So that my booking can be confirmed and payment recorded"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ZarinPalPaymentVerificationFeature(ZarinPalPaymentVerificationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            global::Reqnroll.Table table237 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table237.AddRow(new string[] {
                        "BusinessName",
                        "Test Salon"});
            table237.AddRow(new string[] {
                        "BusinessType",
                        "BeautySalon"});
            table237.AddRow(new string[] {
                        "Email",
                        "salon@example.com"});
            await testRunner.GivenAsync("a registered provider exists with:", ((string)(null)), table237, "Given ");
            global::Reqnroll.Table table238 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table238.AddRow(new string[] {
                        "Amount",
                        "500000"});
            table238.AddRow(new string[] {
                        "Currency",
                        "IRR"});
            table238.AddRow(new string[] {
                        "Status",
                        "Confirmed"});
            await testRunner.AndAsync("a booking exists for the provider with:", ((string)(null)), table238, "And ");
            global::Reqnroll.Table table239 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table239.AddRow(new string[] {
                        "Amount",
                        "500000"});
            table239.AddRow(new string[] {
                        "Description",
                        "Booking payment"});
            table239.AddRow(new string[] {
                        "Mobile",
                        "09123456789"});
            await testRunner.AndAsync("a ZarinPal payment request has been created with:", ((string)(null)), table239, "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successfully verify payment after customer completes it on ZarinPal")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Successfully verify payment after customer completes it on ZarinPal")]
        public async System.Threading.Tasks.Task SuccessfullyVerifyPaymentAfterCustomerCompletesItOnZarinPal()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully verify payment after customer completes it on ZarinPal", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table240 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table240.AddRow(new string[] {
                            "Authority",
                            "{LastAuthority}"});
                table240.AddRow(new string[] {
                            "Status",
                            "OK"});
                await testRunner.WhenAsync("ZarinPal redirects to callback with:", ((string)(null)), table240, "When ");
                await testRunner.ThenAsync("the callback response should redirect to success page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should have status \"Paid\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should have \"RefNumber\" stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should have \"CardPan\" stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("a \"PaymentVerifiedEvent\" domain event should be published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Handle user cancellation on ZarinPal payment page")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Handle user cancellation on ZarinPal payment page")]
        public async System.Threading.Tasks.Task HandleUserCancellationOnZarinPalPaymentPage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle user cancellation on ZarinPal payment page", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer navigated to ZarinPal payment page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the customer clicks cancel button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table241 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table241.AddRow(new string[] {
                            "Authority",
                            "{LastAuthority}"});
                table241.AddRow(new string[] {
                            "Status",
                            "NOK"});
                await testRunner.AndAsync("ZarinPal redirects to callback with:", ((string)(null)), table241, "And ");
                await testRunner.ThenAsync("the callback response should redirect to failure page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should have status \"Failed\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment failure reason should be \"User cancelled the payment\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify payment with card information captured")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Verify payment with card information captured")]
        public async System.Threading.Tasks.Task VerifyPaymentWithCardInformationCaptured()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify payment with card information captured", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table242 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table242.AddRow(new string[] {
                            "CardPan",
                            "6274****1234"});
                table242.AddRow(new string[] {
                            "Fee",
                            "5000"});
                await testRunner.AndAsync("ZarinPal captured card details:", ((string)(null)), table242, "And ");
                global::Reqnroll.Table table243 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table243.AddRow(new string[] {
                            "Authority",
                            "{LastAuthority}"});
                table243.AddRow(new string[] {
                            "Status",
                            "OK"});
                await testRunner.WhenAsync("ZarinPal redirects to callback with:", ((string)(null)), table243, "When ");
                await testRunner.ThenAsync("the payment should have status \"Paid\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table244 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table244.AddRow(new string[] {
                            "CardPan",
                            "6274****1234"});
                table244.AddRow(new string[] {
                            "Fee",
                            "5000"});
                await testRunner.AndAsync("the payment should have these details:", ((string)(null)), table244, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate net amount after fee deduction")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Calculate net amount after fee deduction")]
        public async System.Threading.Tasks.Task CalculateNetAmountAfterFeeDeduction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculate net amount after fee deduction", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("ZarinPal charged a fee of 5000 Rials", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("the payment is verified successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the payment net amount should be 495000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Handle payment verification failure from ZarinPal")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Handle payment verification failure from ZarinPal")]
        public async System.Threading.Tasks.Task HandlePaymentVerificationFailureFromZarinPal()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle payment verification failure from ZarinPal", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment request exists with authority", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I verify the payment with ZarinPal API", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("ZarinPal returns verification error \"-53\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("the payment should have status \"Failed\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment failure reason should contain \"verification unsuccessful\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Handle already verified payment (Code 101)")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Handle already verified payment (Code 101)")]
        public async System.Threading.Tasks.Task HandleAlreadyVerifiedPaymentCode101()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle already verified payment (Code 101)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment was already verified successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table245 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table245.AddRow(new string[] {
                            "Authority",
                            "{LastAuthority}"});
                table245.AddRow(new string[] {
                            "Status",
                            "OK"});
                await testRunner.WhenAsync("ZarinPal redirects to callback again with:", ((string)(null)), table245, "When ");
                await testRunner.ThenAsync("the verification should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should remain \"Paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("no duplicate transaction should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fail verification when payment not found")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Fail verification when payment not found")]
        public async System.Threading.Tasks.Task FailVerificationWhenPaymentNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fail verification when payment not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table246 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table246.AddRow(new string[] {
                            "Authority",
                            "A_NONEXISTENT_AUTHORITY_12345"});
                table246.AddRow(new string[] {
                            "Status",
                            "OK"});
                await testRunner.WhenAsync("ZarinPal redirects to callback with:", ((string)(null)), table246, "When ");
                await testRunner.ThenAsync("the callback response should return error \"Payment not found\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response status code should be 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify payment and update booking status")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Verify payment and update booking status")]
        public async System.Threading.Tasks.Task VerifyPaymentAndUpdateBookingStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify payment and update booking status", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the payment is verified successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the payment should have status \"Paid\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the associated booking should be updated accordingly", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Handle verification with missing card PAN")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Handle verification with missing card PAN")]
        public async System.Threading.Tasks.Task HandleVerificationWithMissingCardPAN()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle verification with missing card PAN", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("ZarinPal verifies payment without CardPan", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the payment should have status \"Paid\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment CardPan should be null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify payment creates transaction record")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Verify payment creates transaction record")]
        public async System.Threading.Tasks.Task VerifyPaymentCreatesTransactionRecord()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify payment creates transaction record", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the payment is verified successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table247 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table247.AddRow(new string[] {
                            "Type",
                            "Verification"});
                table247.AddRow(new string[] {
                            "Status",
                            "Succeeded"});
                table247.AddRow(new string[] {
                            "RefNumber",
                            "not-null"});
                await testRunner.ThenAsync("a transaction record should exist with:", ((string)(null)), table247, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Frontend redirect to success page with payment details")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Frontend redirect to success page with payment details")]
        public async System.Threading.Tasks.Task FrontendRedirectToSuccessPageWithPaymentDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Frontend redirect to success page with payment details", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer completed the payment on ZarinPal gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the payment is verified successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the callback should redirect to frontend success URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table248 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table248.AddRow(new string[] {
                            "paymentId",
                            "{LastPaymentId}"});
                table248.AddRow(new string[] {
                            "refNumber",
                            "{PaymentRefNumber}"});
                table248.AddRow(new string[] {
                            "status",
                            "success"});
                await testRunner.AndAsync("the redirect URL should contain query parameters:", ((string)(null)), table248, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Frontend redirect to failure page with error details")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Frontend redirect to failure page with error details")]
        public async System.Threading.Tasks.Task FrontendRedirectToFailurePageWithErrorDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Frontend redirect to failure page with error details", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the customer navigated to ZarinPal payment page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the customer clicks cancel button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the callback should redirect to frontend failure URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table249 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table249.AddRow(new string[] {
                            "paymentId",
                            "{LastPaymentId}"});
                table249.AddRow(new string[] {
                            "status",
                            "failed"});
                table249.AddRow(new string[] {
                            "reason",
                            "User cancelled"});
                await testRunner.AndAsync("the redirect URL should contain query parameters:", ((string)(null)), table249, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Concurrent verification requests should be handled safely")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Verification")]
        [Xunit.TraitAttribute("Description", "Concurrent verification requests should be handled safely")]
        public async System.Threading.Tasks.Task ConcurrentVerificationRequestsShouldBeHandledSafely()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Concurrent verification requests should be handled safely", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment request exists with authority", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("multiple verification requests are sent simultaneously", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("only one verification should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should have status \"Paid\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("no duplicate transactions should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ZarinPalPaymentVerificationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ZarinPalPaymentVerificationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
