// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Payments.ZarinPal
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ZarinPalPaymentRefundsFeature : object, Xunit.IClassFixture<ZarinPalPaymentRefundsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Payments/ZarinPal", "ZarinPal Payment Refunds", "    As a provider or admin\r\n    I want to refund ZarinPal payments\r\n    So that I" +
                " can return money to customers when needed", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ZarinPalPaymentRefundsFeature(ZarinPalPaymentRefundsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            global::Reqnroll.Table table297 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table297.AddRow(new string[] {
                        "BusinessName",
                        "Beauty Center"});
            table297.AddRow(new string[] {
                        "BusinessType",
                        "BeautySalon"});
            await testRunner.GivenAsync("a registered provider exists with:", ((string)(null)), table297, "Given ");
            global::Reqnroll.Table table298 = new global::Reqnroll.Table(new string[] {
                        "Field",
                        "Value"});
            table298.AddRow(new string[] {
                        "Amount",
                        "500000"});
            table298.AddRow(new string[] {
                        "Currency",
                        "IRR"});
            table298.AddRow(new string[] {
                        "Status",
                        "Paid"});
            table298.AddRow(new string[] {
                        "Authority",
                        "A123456789"});
            table298.AddRow(new string[] {
                        "RefNumber",
                        "987654321"});
            table298.AddRow(new string[] {
                        "CardPan",
                        "6274****1234"});
            await testRunner.AndAsync("a completed ZarinPal payment exists with:", ((string)(null)), table298, "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successfully refund full payment amount")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Successfully refund full payment amount")]
        public async System.Threading.Tasks.Task SuccessfullyRefundFullPaymentAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully refund full payment amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table299 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table299.AddRow(new string[] {
                            "Amount",
                            "500000"});
                table299.AddRow(new string[] {
                            "Reason",
                            "Customer requested refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table299, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should indicate refund success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment should have status \"Refunded\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the refunded amount should be 500000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successfully process partial refund")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Successfully process partial refund")]
        public async System.Threading.Tasks.Task SuccessfullyProcessPartialRefund()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully process partial refund", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table300 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table300.AddRow(new string[] {
                            "Amount",
                            "200000"});
                table300.AddRow(new string[] {
                            "Reason",
                            "Partial service refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table300, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should have status \"PartiallyRefunded\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the refunded amount should be 200000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment net amount should be 300000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Process multiple partial refunds")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Process multiple partial refunds")]
        public async System.Threading.Tasks.Task ProcessMultiplePartialRefunds()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Process multiple partial refunds", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("I refund 150000 Rials with reason \"First partial refund\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I refund 100000 Rials with reason \"Second partial refund\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("the total refunded amount should be 250000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should have status \"PartiallyRefunded\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the payment net amount should be 250000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full refund after partial refunds")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Full refund after partial refunds")]
        public async System.Threading.Tasks.Task FullRefundAfterPartialRefunds()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Full refund after partial refunds", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the payment has been partially refunded 200000 Rials", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table301 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table301.AddRow(new string[] {
                            "Amount",
                            "300000"});
                table301.AddRow(new string[] {
                            "Reason",
                            "Complete the refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table301, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should have status \"Refunded\" in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the total refunded amount should be 500000", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fail to refund more than payment amount")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Fail to refund more than payment amount")]
        public async System.Threading.Tasks.Task FailToRefundMoreThanPaymentAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fail to refund more than payment amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table302 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table302.AddRow(new string[] {
                            "Amount",
                            "600000"});
                table302.AddRow(new string[] {
                            "Reason",
                            "Invalid refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table302, "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Refund amount exceeds available amount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fail to refund already fully refunded payment")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Fail to refund already fully refunded payment")]
        public async System.Threading.Tasks.Task FailToRefundAlreadyFullyRefundedPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Fail to refund already fully refunded payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the payment has been fully refunded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table303 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table303.AddRow(new string[] {
                            "Amount",
                            "100000"});
                table303.AddRow(new string[] {
                            "Reason",
                            "Double refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table303, "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Payment is already fully refunded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund with detailed description")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund with detailed description")]
        public async System.Threading.Tasks.Task RefundWithDetailedDescription()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund with detailed description", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table304 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table304.AddRow(new string[] {
                            "Amount",
                            "250000"});
                table304.AddRow(new string[] {
                            "Reason",
                            "Service cancelled"});
                table304.AddRow(new string[] {
                            "Description",
                            "Customer cancelled due to emergency"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table304, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refund should have the description stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund creates transaction record")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund creates transaction record")]
        public async System.Threading.Tasks.Task RefundCreatesTransactionRecord()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund creates transaction record", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table305 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table305.AddRow(new string[] {
                            "Amount",
                            "300000"});
                table305.AddRow(new string[] {
                            "Reason",
                            "Test refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table305, "When ");
                global::Reqnroll.Table table306 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table306.AddRow(new string[] {
                            "Type",
                            "Refund"});
                table306.AddRow(new string[] {
                            "Amount",
                            "300000"});
                table306.AddRow(new string[] {
                            "Status",
                            "Succeeded"});
                await testRunner.ThenAsync("a refund transaction should exist with:", ((string)(null)), table306, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate net amount correctly after fee and refund")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Calculate net amount correctly after fee and refund")]
        public async System.Threading.Tasks.Task CalculateNetAmountCorrectlyAfterFeeAndRefund()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculate net amount correctly after fee and refund", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("the payment has fee of 5000 Rials", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I refund 200000 Rials", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the payment net amount should be 295000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund minimum amount validation")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund minimum amount validation")]
        public async System.Threading.Tasks.Task RefundMinimumAmountValidation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund minimum amount validation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table307 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table307.AddRow(new string[] {
                            "Amount",
                            "0"});
                table307.AddRow(new string[] {
                            "Reason",
                            "Zero refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table307, "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain validation error for \"Amount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund pending payment should fail")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund pending payment should fail")]
        public async System.Threading.Tasks.Task RefundPendingPaymentShouldFail()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund pending payment should fail", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment exists with status \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I attempt to refund the payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Cannot refund payment that is not paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund failed payment should fail")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund failed payment should fail")]
        public async System.Threading.Tasks.Task RefundFailedPaymentShouldFail()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund failed payment should fail", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment exists with status \"Failed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I attempt to refund the payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Cannot refund failed payment\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="ZarinPal API refund failure handling")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "ZarinPal API refund failure handling")]
        public async System.Threading.Tasks.Task ZarinPalAPIRefundFailureHandling()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ZarinPal API refund failure handling", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table308 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table308.AddRow(new string[] {
                            "Amount",
                            "100000"});
                table308.AddRow(new string[] {
                            "Reason",
                            "Test refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table308, "When ");
                await testRunner.AndAsync("ZarinPal API returns refund error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("the response status code should be 500", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the payment should still have status \"Paid\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("the refunded amount should remain 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Idempotent refund requests")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Idempotent refund requests")]
        public async System.Threading.Tasks.Task IdempotentRefundRequests()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Idempotent refund requests", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a refund request with idempotency key \"refund-123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I send the same refund request twice", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("only one refund should be processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("both responses should return the same result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refund authorization check")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Refund authorization check")]
        public async System.Threading.Tasks.Task RefundAuthorizationCheck()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refund authorization check", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am logged in as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I attempt to refund a payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Unauthorized\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Provider can refund their own payments")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Provider can refund their own payments")]
        public async System.Threading.Tasks.Task ProviderCanRefundTheirOwnPayments()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Provider can refund their own payments", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am logged in as the provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table309 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table309.AddRow(new string[] {
                            "Amount",
                            "100000"});
                table309.AddRow(new string[] {
                            "Reason",
                            "Provider initiated"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table309, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refund should be processed successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Admin can refund any payment")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Refunds")]
        [Xunit.TraitAttribute("Description", "Admin can refund any payment")]
        public async System.Threading.Tasks.Task AdminCanRefundAnyPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can refund any payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table310 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table310.AddRow(new string[] {
                            "Amount",
                            "150000"});
                table310.AddRow(new string[] {
                            "Reason",
                            "Admin refund"});
                await testRunner.WhenAsync("I send a POST request to \"/api/v1/payments/refund\" with:", ((string)(null)), table310, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the refund should be processed successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ZarinPalPaymentRefundsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ZarinPalPaymentRefundsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
