// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Booksy.ServiceCatalog.IntegrationTests.Features.Payments.ZarinPal
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ZarinPalPaymentReconciliationFeature : object, Xunit.IClassFixture<ZarinPalPaymentReconciliationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features/Payments/ZarinPal", "ZarinPal Payment Reconciliation", "    As a finance admin\r\n    I want to reconcile ZarinPal payments\r\n    So that I " +
                "can ensure payment records match ZarinPal gateway records", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public ZarinPalPaymentReconciliationFeature(ZarinPalPaymentReconciliationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("I am logged in as a finance admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
            await testRunner.AndAsync("multiple providers have ZarinPal payments", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Generate daily reconciliation report")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Generate daily reconciliation report")]
        public async System.Threading.Tasks.Task GenerateDailyReconciliationReport()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Generate daily reconciliation report", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are payments on 2024-01-15", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table276 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table276.AddRow(new string[] {
                            "StartDate",
                            "2024-01-15"});
                table276.AddRow(new string[] {
                            "EndDate",
                            "2024-01-15"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation\" with parameters:", ((string)(null)), table276, "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the report should contain all payments from that date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="View reconciliation summary for date range")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "View reconciliation summary for date range")]
        public async System.Threading.Tasks.Task ViewReconciliationSummaryForDateRange()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View reconciliation summary for date range", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table277 = new global::Reqnroll.Table(new string[] {
                            "Date",
                            "Amount",
                            "Status",
                            "Method"});
                table277.AddRow(new string[] {
                            "2024-01-15",
                            "500000",
                            "Paid",
                            "ZarinPal"});
                table277.AddRow(new string[] {
                            "2024-01-16",
                            "300000",
                            "Paid",
                            "ZarinPal"});
                table277.AddRow(new string[] {
                            "2024-01-17",
                            "200000",
                            "Failed",
                            "ZarinPal"});
                table277.AddRow(new string[] {
                            "2024-01-18",
                            "400000",
                            "Paid",
                            "ZarinPal"});
                await testRunner.GivenAsync("there are these payments:", ((string)(null)), table277, "Given ");
                global::Reqnroll.Table table278 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table278.AddRow(new string[] {
                            "StartDate",
                            "2024-01-15"});
                table278.AddRow(new string[] {
                            "EndDate",
                            "2024-01-18"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation\" with parameters:", ((string)(null)), table278, "When ");
                global::Reqnroll.Table table279 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table279.AddRow(new string[] {
                            "TotalPayments",
                            "4"});
                table279.AddRow(new string[] {
                            "SuccessfulCount",
                            "3"});
                table279.AddRow(new string[] {
                            "FailedCount",
                            "1"});
                table279.AddRow(new string[] {
                            "TotalAmount",
                            "1400000"});
                table279.AddRow(new string[] {
                            "SuccessfulAmount",
                            "1200000"});
                await testRunner.ThenAsync("the response should contain:", ((string)(null)), table279, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filter reconciliation by payment method")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Filter reconciliation by payment method")]
        public async System.Threading.Tasks.Task FilterReconciliationByPaymentMethod()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter reconciliation by payment method", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are payments with different methods", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table280 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table280.AddRow(new string[] {
                            "PaymentMethod",
                            "ZarinPal"});
                table280.AddRow(new string[] {
                            "StartDate",
                            "2024-01-01"});
                table280.AddRow(new string[] {
                            "EndDate",
                            "2024-01-31"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation\" with parameters:", ((string)(null)), table280, "When ");
                await testRunner.ThenAsync("the report should only include ZarinPal payments", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="View detailed transaction list in reconciliation")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "View detailed transaction list in reconciliation")]
        public async System.Threading.Tasks.Task ViewDetailedTransactionListInReconciliation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View detailed transaction list in reconciliation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are 10 payments on 2024-01-15", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I request detailed reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table281 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Present"});
                table281.AddRow(new string[] {
                            "PaymentId",
                            "yes"});
                table281.AddRow(new string[] {
                            "Authority",
                            "yes"});
                table281.AddRow(new string[] {
                            "RefNumber",
                            "yes"});
                table281.AddRow(new string[] {
                            "Amount",
                            "yes"});
                table281.AddRow(new string[] {
                            "Fee",
                            "yes"});
                table281.AddRow(new string[] {
                            "Status",
                            "yes"});
                table281.AddRow(new string[] {
                            "CardPan",
                            "yes"});
                table281.AddRow(new string[] {
                            "CreatedAt",
                            "yes"});
                await testRunner.ThenAsync("the response should include all transaction details:", ((string)(null)), table281, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Identify discrepancies in payment amounts")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Identify discrepancies in payment amounts")]
        public async System.Threading.Tasks.Task IdentifyDiscrepanciesInPaymentAmounts()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Identify discrepancies in payment amounts", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment has different amounts in database and gateway", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I run reconciliation check", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the discrepancy should be flagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table282 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Present"});
                table282.AddRow(new string[] {
                            "ExpectedAmount",
                            "yes"});
                table282.AddRow(new string[] {
                            "ActualAmount",
                            "yes"});
                table282.AddRow(new string[] {
                            "Difference",
                            "yes"});
                await testRunner.AndAsync("the report should show:", ((string)(null)), table282, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Group reconciliation by provider")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Group reconciliation by provider")]
        public async System.Threading.Tasks.Task GroupReconciliationByProvider()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Group reconciliation by provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("multiple providers have payments", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table283 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table283.AddRow(new string[] {
                            "GroupBy",
                            "Provider"});
                table283.AddRow(new string[] {
                            "StartDate",
                            "2024-01-01"});
                table283.AddRow(new string[] {
                            "EndDate",
                            "2024-01-31"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation\" with parameters:", ((string)(null)), table283, "When ");
                await testRunner.ThenAsync("the report should be grouped by provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("each group should show provider statistics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate total fees collected by ZarinPal")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Calculate total fees collected by ZarinPal")]
        public async System.Threading.Tasks.Task CalculateTotalFeesCollectedByZarinPal()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculate total fees collected by ZarinPal", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table284 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Fee"});
                table284.AddRow(new string[] {
                            "500000",
                            "5000"});
                table284.AddRow(new string[] {
                            "300000",
                            "3000"});
                table284.AddRow(new string[] {
                            "200000",
                            "2000"});
                await testRunner.GivenAsync("there are these completed payments with fees:", ((string)(null)), table284, "Given ");
                await testRunner.WhenAsync("I request reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table285 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table285.AddRow(new string[] {
                            "TotalFees",
                            "10000"});
                await testRunner.ThenAsync("the response should contain:", ((string)(null)), table285, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Track refunds in reconciliation")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Track refunds in reconciliation")]
        public async System.Threading.Tasks.Task TrackRefundsInReconciliation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Track refunds in reconciliation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table286 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Status",
                            "RefundedAmount"});
                table286.AddRow(new string[] {
                            "500000",
                            "Paid",
                            "0"});
                table286.AddRow(new string[] {
                            "400000",
                            "Refunded",
                            "400000"});
                table286.AddRow(new string[] {
                            "300000",
                            "PartiallyRefunded",
                            "150000"});
                await testRunner.GivenAsync("there are these payments:", ((string)(null)), table286, "Given ");
                await testRunner.WhenAsync("I request reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table287 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table287.AddRow(new string[] {
                            "TotalRefunds",
                            "550000"});
                table287.AddRow(new string[] {
                            "RefundedPayments",
                            "2"});
                await testRunner.ThenAsync("the response should contain:", ((string)(null)), table287, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Identify missing verification for payment requests")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Identify missing verification for payment requests")]
        public async System.Threading.Tasks.Task IdentifyMissingVerificationForPaymentRequests()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Identify missing verification for payment requests", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment request was created but never verified", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I run reconciliation check", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the unverified payment should be flagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("it should appear in \"Pending Verification\" section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Export reconciliation report as Excel")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Export reconciliation report as Excel")]
        public async System.Threading.Tasks.Task ExportReconciliationReportAsExcel()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Export reconciliation report as Excel", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there is reconciliation data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table288 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table288.AddRow(new string[] {
                            "Format",
                            "Excel"});
                table288.AddRow(new string[] {
                            "StartDate",
                            "2024-01-01"});
                table288.AddRow(new string[] {
                            "EndDate",
                            "2024-01-31"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation/export\" with parameters:" +
                        "", ((string)(null)), table288, "When ");
                await testRunner.ThenAsync("the response should be an Excel file", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table289 = new global::Reqnroll.Table(new string[] {
                            "Sheet"});
                table289.AddRow(new string[] {
                            "Summary"});
                table289.AddRow(new string[] {
                            "Transactions"});
                table289.AddRow(new string[] {
                            "Refunds"});
                table289.AddRow(new string[] {
                            "Discrepancies"});
                await testRunner.AndAsync("the file should contain multiple sheets:", ((string)(null)), table289, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Daily automated reconciliation check")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Daily automated reconciliation check")]
        public async System.Threading.Tasks.Task DailyAutomatedReconciliationCheck()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Daily automated reconciliation check", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("it is end of day", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the automated reconciliation job runs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("a reconciliation report should be generated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("any discrepancies should be reported", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Compare with ZarinPal settlement report")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Compare with ZarinPal settlement report")]
        public async System.Threading.Tasks.Task CompareWithZarinPalSettlementReport()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Compare with ZarinPal settlement report", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I have ZarinPal\'s settlement report", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I upload the settlement report for comparison", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the system should match payments", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("highlight any mismatches", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Track payment status changes")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Track payment status changes")]
        public async System.Threading.Tasks.Task TrackPaymentStatusChanges()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Track payment status changes", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("a payment changed status during the day", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I view reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the status history should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate net settlement amount")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Calculate net settlement amount")]
        public async System.Threading.Tasks.Task CalculateNetSettlementAmount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculate net settlement amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table290 = new global::Reqnroll.Table(new string[] {
                            "Type",
                            "Amount"});
                table290.AddRow(new string[] {
                            "Payment",
                            "500000"});
                table290.AddRow(new string[] {
                            "Payment",
                            "300000"});
                table290.AddRow(new string[] {
                            "Refund",
                            "150000"});
                table290.AddRow(new string[] {
                            "Payment",
                            "200000"});
                await testRunner.GivenAsync("there are these payments and refunds:", ((string)(null)), table290, "Given ");
                await testRunner.WhenAsync("I request reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table291 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table291.AddRow(new string[] {
                            "TotalPayments",
                            "1000000"});
                table291.AddRow(new string[] {
                            "TotalRefunds",
                            "150000"});
                table291.AddRow(new string[] {
                            "NetSettlement",
                            "850000"});
                await testRunner.ThenAsync("the response should contain:", ((string)(null)), table291, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="View reconciliation by hour for fraud detection")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "View reconciliation by hour for fraud detection")]
        public async System.Threading.Tasks.Task ViewReconciliationByHourForFraudDetection()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View reconciliation by hour for fraud detection", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are payments throughout the day", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table292 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table292.AddRow(new string[] {
                            "Date",
                            "2024-01-15"});
                table292.AddRow(new string[] {
                            "GroupBy",
                            "Hour"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation\" with parameters:", ((string)(null)), table292, "When ");
                await testRunner.ThenAsync("the response should show hourly breakdown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("unusual patterns should be highlighted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reconcile failed payment attempts")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Reconcile failed payment attempts")]
        public async System.Threading.Tasks.Task ReconcileFailedPaymentAttempts()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reconcile failed payment attempts", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table293 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Status",
                            "Attempts"});
                table293.AddRow(new string[] {
                            "500000",
                            "Paid",
                            "1"});
                table293.AddRow(new string[] {
                            "300000",
                            "Failed",
                            "3"});
                table293.AddRow(new string[] {
                            "200000",
                            "Paid",
                            "2"});
                await testRunner.GivenAsync("there are these payment attempts:", ((string)(null)), table293, "Given ");
                await testRunner.WhenAsync("I request reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                global::Reqnroll.Table table294 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table294.AddRow(new string[] {
                            "TotalAttempts",
                            "6"});
                table294.AddRow(new string[] {
                            "FailureRate",
                            "50"});
                await testRunner.ThenAsync("it should show:", ((string)(null)), table294, "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Monthly reconciliation summary")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Monthly reconciliation summary")]
        public async System.Threading.Tasks.Task MonthlyReconciliationSummary()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Monthly reconciliation summary", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("there are payments throughout January 2024", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                global::Reqnroll.Table table295 = new global::Reqnroll.Table(new string[] {
                            "Parameter",
                            "Value"});
                table295.AddRow(new string[] {
                            "Year",
                            "2024"});
                table295.AddRow(new string[] {
                            "Month",
                            "1"});
                await testRunner.WhenAsync("I send a GET request to \"/api/v1/payments/reconciliation/monthly\" with parameters" +
                        ":", ((string)(null)), table295, "When ");
                await testRunner.ThenAsync("the response should contain monthly summary", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("daily breakdowns should be included", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Unauthorized access to reconciliation")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Unauthorized access to reconciliation")]
        public async System.Threading.Tasks.Task UnauthorizedAccessToReconciliation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access to reconciliation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am logged in as a customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I attempt to access reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error \"Unauthorized\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Unauthorized access for regular provider")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Unauthorized access for regular provider")]
        public async System.Threading.Tasks.Task UnauthorizedAccessForRegularProvider()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Unauthorized access for regular provider", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am logged in as a provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I attempt to access system-wide reconciliation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should only see my own payment data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Finance admin has full reconciliation access")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Finance admin has full reconciliation access")]
        public async System.Threading.Tasks.Task FinanceAdminHasFullReconciliationAccess()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Finance admin has full reconciliation access", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am logged in as a finance admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I request reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("I should see all providers\' payments", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see all payment methods", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Schedule automatic reconciliation reports")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Schedule automatic reconciliation reports")]
        public async System.Threading.Tasks.Task ScheduleAutomaticReconciliationReports()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Schedule automatic reconciliation reports", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I configure automatic reports", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I set schedule to daily at 23:00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("reconciliation reports should be generated daily", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("emailed to finance team", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Audit trail for reconciliation access")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Audit trail for reconciliation access")]
        public async System.Threading.Tasks.Task AuditTrailForReconciliationAccess()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Audit trail for reconciliation access", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I access a reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("the report is generated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("an audit log entry should be created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                global::Reqnroll.Table table296 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Present"});
                table296.AddRow(new string[] {
                            "UserId",
                            "yes"});
                table296.AddRow(new string[] {
                            "Timestamp",
                            "yes"});
                table296.AddRow(new string[] {
                            "DateRange",
                            "yes"});
                table296.AddRow(new string[] {
                            "ReportType",
                            "yes"});
                await testRunner.AndAsync("it should record:", ((string)(null)), table296, "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Handle timezone differences in reconciliation")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Handle timezone differences in reconciliation")]
        public async System.Threading.Tasks.Task HandleTimezoneDifferencesInReconciliation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Handle timezone differences in reconciliation", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("payments were made in different timezones", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I generate reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("all timestamps should be normalized to UTC", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("displayed in selected timezone", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Real-time reconciliation dashboard")]
        [Xunit.TraitAttribute("FeatureTitle", "ZarinPal Payment Reconciliation")]
        [Xunit.TraitAttribute("Description", "Real-time reconciliation dashboard")]
        public async System.Threading.Tasks.Task Real_TimeReconciliationDashboard()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Real-time reconciliation dashboard", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("I am viewing reconciliation dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("new payments are processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the dashboard should update in real-time", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("show current day statistics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ZarinPalPaymentReconciliationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ZarinPalPaymentReconciliationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
